### ISSUE TITLE
Bugs in maven.

### ISSUE THREAD

**Issue by N3zp0w3r** [ruany/LiteBansAPI#1]
So, i believe it's not a bug, it's my dumbness, but i cloned it and there's no src/main/java folder.
Cloned it that way - https://gyazo.com/302dbe7512b72983e06214ec60ad57dc
And got that - https://gyazo.com/7b82cea1a2b9f9aa9bd235bea33b64a0
Isn't there supposed to be a src/main/java Source folder, not a folder? How do i fix it?
Also i added to my other plugin's pom.xml this:
<dependency>
  <groupId>litebans</groupId>
  <artifactId>api</artifactId>
  <version>0.2</version>
  <scope>provided</scope>
</dependency>
And it says that it's Missing artifact litebans:api:jar:0.2
Probably it's my dumbness.

**Comment by ruany** [comment]
You need to install the Maven artifact locally, that's what `mvn clean install` does.

https://stackoverflow.com/questions/37999457/what-is-the-difference-between-maven-install-and-maven-build-with-m2eclipse

Not much else I can help with, though, I don't work with Eclipse.
