### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by BrainStone** [ruany/LiteBansAPI#10]
It would be really cool if the API was available on a maven repo, so it can be downloaded instead of having to be compiled locally.

**Comment by ruany** [comment]
Feel free to suggest a repo where it can be uploaded to. I don't know if it qualifies for the Central Repository since it's an API for proprietary software.

In the meantime: https://github.com/ruany/LiteBansAPI/releases

**Comment by BrainStone** [comment]
I sadly can't use github releases as a maven repo.

And I've heard https://jitpack.io/ is a good place.

**Comment by ruany** [comment]
https://jitpack.io/#ruany/LiteBansAPI/0.3

Looks like they build it automatically when you request it.

**Comment by BrainStone** [comment]
Great!
