### ISSUE TITLE
Problems hooking up with the API. Again.

### ISSUE THREAD

**Issue by N3zp0w3r** [ruany/LiteBansAPI#2]
Hello. I recently switched to InteliJ, because you told me that you don't use Eclipse. So, how do i hook up with the API with Maven? I'd like to make a cooldown on successful ban. Thanks.

**Comment by ruany** [comment]
Maven Projects -> api -> Lifecycle -> install

https://www.jetbrains.com/help/idea/2016.2/getting-started-with-maven.html#execute_maven_goal
