### ISSUE TITLE
--sender does not change executor in entry event

### ISSUE THREAD

**Issue by Pugabyte** [ruany/LiteBansAPI#3]
![](https://i.imgur.com/QvZ4PYZ.png)

Additionally, in /history, it notes that previous mutes/bans were removed by Console, instead of the `--sender` argument. 

Possibly intended behavior, but it seemed odd to me.

**Comment by ruany** [comment]
Are you checking the executor name or the UUID? The UUID will not change.

**Comment by Pugabyte** [comment]
Gotcha, thanks
