### ISSUE TITLE
No API for banning

### ISSUE THREAD

**Issue by EonZombiecrafter** [ruany/LiteBansAPI#4]
Hello,
I saw that you said that there's no need for an API on banning players. That is not true. What I want to do is open GUI window, when admin executes  /ban, /tempban etc. And that's why I need some kind of method in your plugin to preform ban via your plugin unless I cannot do it. Please consider on adding methods for banning, temp. banning etc. 
Thank you!
EonZombie from ExtronusPvP team

**Comment by ruany** [comment]
Once you've overridden the /ban command, you can execute /litebans:ban with whatever arguments are necessary. API is not required to do this.
Also, you don't need to override /ban, you can use e.g. /bangui or /bg, or hook up a custom item for it.
