### ISSUE TITLE
More API

### ISSUE THREAD

**Issue by LoYungSum** [ruany/LiteBansAPI#5]
I am in a spigot server and I want to ban a player, but the owner just want to install the litebans plugin on bungeecord, so can you create an API for banning players on bungee while the plugin is installed on spigot

**Comment by ruany** [comment]
The API is there if you use it with a BungeeCord plugin.

To bridge down to Spigot, it would require a Spigot-side plugin, at which point you might as well just install LiteBans on Spigot anyway.

**Comment by LoYungSum** [comment]
Any API suggest?

**Comment by ruany** [comment]
I meant, if you build a BungeeCord plugin and install it on BungeeCord, you'll be able to use the LiteBans API under BungeeCord. 

You want me to create a bridge API. The plugin already has the ability to bridge down to Spigot by being installed under Spigot.

**Comment by LoYungSum** [comment]
But my plugin needs to implements to AAC, antiaura and other anticheats installed on spigot

**Comment by ruany** [comment]
Then install LiteBans on Spigot.

**Comment by LoYungSum** [comment]
The owner doesn't want to use much extra resources, so he doesn't want to install litebans on spigot

**Comment by LoYungSum** [comment]
He's so dump, right?
