### ISSUE TITLE
Java Docs

### ISSUE THREAD

**Issue by dorilahav1234561** [ruany/LiteBansAPI#6]
Dear Ruany,
I have been trying to use your API but I couldn't,
The main reason why I couldn't use it is that there is lack of documentation for it.
What I mean is that in order to get punishment type I need to enter a String that I don't really know, you could have used Enums to solve this easily.
Another thing will be the fact that you are not using the Spigot built-in Events system which is pretty dumb as it's just making it harder for other developers.
One more thing will be that there is no real documentation for each method in your API. if you could add that it will be much easier to use your API.
Thank you,
Dori_mon

**Comment by ruany** [comment]
>What I mean is that in order to get punishment type I need to enter a String that I don't really know, you could have used Enums to solve this easily.

It's already documented.
https://github.com/ruany/LiteBansAPI/blob/master/src/main/java/litebans/api/Entry.java#L16-L19
```type = {ban,mute,warn,kick}```

>Another thing will be the fact that you are not using the Spigot built-in Events system which is pretty dumb as it's just making it harder for other developers.

Every single event system that I support I would have to create classes for.

If I used the Bukkit event system, I would have to build duplicate events for BungeeCord as well. If I added Sponge support, I would \*also\* have to build duplicate events for the Sponge API, making three sets of duplicated classes for every single event.

> One more thing will be that there is no real documentation for each method in your API. if you could add that it will be much easier to use your API.

Everything is documented.
https://github.com/ruany/LiteBansAPI/wiki#examples
