### ISSUE TITLE
Little change in the broadcastSent

### ISSUE THREAD

**Issue by FrankHeijden** [ruany/LiteBansAPI#8]
Hey,

could you make for the broadcastSent a proper method to get the type (e.g. ban, kick, warn, mute, "tried to speak but is muted"), to get the player involved, to get the punisher, and get the reason?

maybe also a suggestion to switch to the Bukkit events system; so we can just have

@ EventHandler
public void onBroadcast(BroadCastEvent e) {
    e.getMessage() (full message, string)
    e.getPunisher() (punisher, player)
    e.getPlayer() (punishedplayer, offlineplayer)
    e.getReason() (reason, string)
    e.getDuration() (duration, string?)
    e.getBannedIP() (IP, string)
    e.getType() (IPBAN, BAN, UNBAN, KICK, MUTE, UNMUTE, WARN, etc; (ENUM BroadCastType))
}

**Comment by ruany** [comment]
Broadcasts don't have that type of metadata. Perhaps you want the entryAdded event?

I'm not switching to the Bukkit events system because I would have to duplicate all of the event classes for BungeeCord as well.

**Comment by FrankHeijden** [comment]
Ah nice, but could you maybe add another getDuration for the entryAdded event? 

getFriendlyDuration(): returns the arg a player specified in the command, e.g. "/tempban John 1month U mad?" would return "1 month"

**Comment by FrankHeijden** [comment]
any updates on this?

**Comment by ruany** [comment]
Added by https://github.com/ruany/LiteBansAPI/commit/a65e3cb09c4189ebe5e9f9f95b535c1668164725

Included in LiteBans 2.2.13 (minor update, no announcement).
